language: node_js
node_js:
  - "0.12"

before_script:
  - npm install -gq bower
  - bower install --dev --config.interactive=0
  - gulp --version
  - bower --version
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

script: gulp ci
